[package]
name = "vfs_common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", default-features = false }
blake2b_simd = { version = "1.0", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
